### ISSUE TITLE
Make metrics and tracing optional

### ISSUE THREAD

**Issue by dontlaugh** [artsmolin/pythogen#22]
This tool is cool because it generates simple code in a single file. :+1: 

I would like to avoid carrying a dependency on prometheus and yaeger/opentracing stuff, however.

Would it be possible to implement a flag that generates http clients exclusively without those features? For now I'm just going to remove it by hand.

**Comment by ErhoSen** [comment]
That sounds good to me, what do you think @artsmolin ?

**Comment by ErhoSen** [comment]
Btw, as far as I know, the OpenTelemetry standard doesn't require direct dependencies (cause it's done via tricky monkey patching). Maybe we should remove those dependencies at all, and bump major version?

**Comment by artsmolin** [comment]
@dontlaugh 
Done. By default, the client is generated without metrics. To add metrics to the client, you must specify the **--metrics** flag.
