### ISSUE TITLE
generate lower-level `httpx.request` method calls

### ISSUE THREAD

**Issue by dontlaugh** [artsmolin/pythogen#23]
The `get` convenience method in httpx does not allow passing a payload/body.

See this discussion:

https://github.com/encode/httpx/discussions/2277

**Comment by dontlaugh** [comment]
I patched my client with this:

```diff
+        from json import dumps
+        content = dumps(json).encode('utf-8')
         try:
-            response = self.client.get(url,  headers=headers_, params=params, auth=auth_)
+            response = self.client.request("GET", url, headers=headers_, params=params, auth=auth_, content=content)
```

As an aside, the `json` temporary variable shadows the json package name; Maybe it could be renamed to _json or _payload.

**Comment by artsmolin** [comment]
https://github.com/artsmolin/pythogen/commit/4c5e28e31cf57925ef309aa31f6f9619dda86a6a
