### ISSUE TITLE
problem with circular references

### ISSUE THREAD

**Issue by mxab** [artsmolin/pythogen#27]
Hi,
I'm currently trying to create a client for Nomad's OpenAPI

https://github.com/hashicorp/nomad-openapi/blob/main/v1/openapi.yaml

It looks like has an issue with components that reference them self again

e.g.:
https://github.com/hashicorp/nomad-openapi/blob/main/v1/openapi.yaml#L4414

```yml
    ObjectDiff:
      properties:
        Fields:
          items:
            $ref: '#/components/schemas/FieldDiff'
          type: array
        Name:
          type: string
        Objects:
          items:
            $ref: '#/components/schemas/ObjectDiff' <-----
          type: array
        Type:
          type: string
      type: object
```

**Comment by artsmolin** [comment]
https://github.com/artsmolin/pythogen/pull/35
